config/routes.rb
Diputados::Application.routes.draw do

  resources :expedientes, :only => [] do
    resources :assets, :only => [:create, :destroy]
  end

  resources :proyectos, :only => [] do
    resources :assets, :only => [:create, :destroy]
  end

  resources :notas, :only => [] do
    resources :assets, :only => [:create, :destroy]
    resources :pases, :only => [:create, :update, :destroy]
  end

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => 'admin/proyectos#index'

end

app/models/nota.rb
class Nota < Expediente

  belongs_to :primer_pase, class_name: Pase
  belongs_to :ultimo_pase, class_name: Pase
  has_many :areas, through: :ultimo_pase

  validates :pases, presence: true

  accepts_nested_attributes_for :pases

  delegate :area, to: :ultimo_pase, prefix: true
  delegate :ingreso, to: :primer_pase

  def year
    ingreso.strftime("%Y")
  end

  def build_pases
    pases.build if pases.empty?
    pases
  end
end

app/views/admin/notas/_form.html.erb
<%= semantic_form_for nota, :url => url || admin_notas_path do |f| %>
  <%= f.inputs 'Detalles generales' do %>
    <%= f.input :numero %>
    <%= f.input :autor %>
    <% if f.object.new_record? %>
      <%= f.semantic_fields_for :pases do |pase| %>
        <%= render partial: 'admin/pases/form_inputs', locals: { pase: pase }%>
      <% end %>
    <% end %>
    <%= f.input :tags_tokens,
      :input_html => {
        "data-pre" => f.object.tags.to_json(:methods => :name), :only => [:id, :name] } %>

  <% end %>
  <%= f.actions %>
<% end %>